# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  首页: /
  归档: /archives
  分类: /categories
  # Tags: /tags
  关于我: /about.html
  #联系我们: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
# github_url: https://github.com/klugjo/hexo-theme-alpha-dust
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
# email_url: test@example.com
# rss_url: \#

# Footer About Text
footer_about: "享受编程和技术所带来的快乐"

# Footer Copyright Line
footer_copyright: "Copyright©Tracy-xu'Blog. All Rights Reserved."
