version: '3'
services:
  mysql:
    image: mysql
    container_name: wpmysql
    environment:
      - MYSQL_DATABASE=wpdb
      - MYSQL_USER=wpdbuser
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=aaaaaa # root 的密码
    volumes:
      - wpdata:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - wpnet
    restart: on-failure
  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DB_USER=wpdbuser
      - WORDPRESS_DB_PASSWORD=123456
    volumes:
      - wpfiles:/var/www/html # 卷
      - ./wp-content:/var/www/html/wp-content # 目录
    ports:
      - '8080:80'
    networks:
      - wpnet
    restart: on-failure
volumes:
  wpdata:
  wpfiles:
networks:
  wpnet:
