version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: lnmp-nginx
    ports:
      - '5000:80'
    volumes:
      - ./www/:/usr/share/nginx/html/:rw
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: 'Asia/Shanghai'
    restart: always

  # php:
  #   image: php:fpm
  #   container_name: lnmp-php
  #   volumes:
  #     - ./www/:/var/www/html/:rw
  #   restart: always
  #   cap_add:
  #     - SYS_PTRACE

  # lnmp 中需使用 php:fpm，而不是 php:latest，nginx 需通过 cgi 与 php 通信
  # 新版 php:fpm 中，连接 mysql，需要安装扩展 docker-php-ext-install mysqli
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: php-mysqli:fpm # 自定义镜像名
    container_name: lnmp-php
    volumes:
      - ./www/:/var/www/html/:rw
    restart: always
    cap_add:
      - SYS_PTRACE

  mysql:
    image: mysql:latest
    container_name: lnmp-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: 'Asia/Shanghai'
